name: Ada CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Alire
      uses: alire-project/setup-alire@v3
      with:
        version: 2.0.1

    - name: Build and Run Tests
      run: |
        alr build
        alr run
